### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by Tiebe** [apeklets/BetterMagister#1]
Will you ever make another update for this?

**Comment by apeklets** [comment]
As far as i know most features broke with Magister version 5 or 6, and since I no longer have access to a Magister account I will not be updating it. 
It's a pretty simple concept though, feel free to copy any code that still works.

One tip: When I originally made this I split all styles into seperate statements, 
it's way better to just make one style statement with all css lines in it. Or even better you could host a .css file somewhere (i.e. on github) and load that into the <head>
